#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys, getopt, random
import os
from pyspark.sql import SparkSession
import pandas as pd

filepath = "hdfs:/user/ct2522/artist"

def newSparkSession():
    # return SparkSession.builder.getOrCreate()
    mem = "7GB"
    spark = (SparkSession.builder.appName("Music_Project")
             .master("yarn")
             .config("sparn.executor.memory", mem)
             .config("sparn.driver.memory", mem)
             .getOrCreate())
    spark.sparkContext.setLogLevel("ERROR")
    return spark

def prepare_gender(file_path,sparkSession=None):
    spark = sparkSession or newSparkSession()

    # This loads the JSON file and returns the gender dataframe
    artists = spark.read.json("hdfs:/user/ct2522/artist")
    artists.createOrReplaceTempView("artists")
    results=spark.sql("SELECT name,gender FROM artists")
    female=results.filter(results.gender=="Female").select(results.name,results.gender)
    male = results.filter(results.gender=="Male").select(results.name,results.gender)
    gender = female.union(male) 
    data_mb=gender.select("*").toPandas()
    df_mb = pd.DataFrame(data_mb,columns=["female","male"])
    return df_mb
# male count = 531 089, female count = 148 097, lost instances = 984 124 



def main():
    df_1=prepare_gender(filepath)
    return df_1.describe()

if __name__ == "__main__":

    main()
